#!/usr/bin/env node
'use strict';

/**
 * generate.js — deterministic assembly of a new Angular project from base/ + bundles/.
 *
 * This script does NOT use AI. Given the same flags, it produces the same output every
 * time. A Claude Code skill is expected to sit in front of this and handle the
 * conversational Q&A, then call this script with plain flags — see CONTEXT.md §2 for
 * why that split exists.
 *
 * Usage:
 *   node generate.js \
 *     --project-name=my-app \
 *     --auth=basic-auth \
 *     --data-layer=rest \
 *     --state=signals-only \
 *     --roles=single-role \
 *     --deploy-target=spa \
 *     --repo=https://github.com/org/my-app.git \
 *     [--out-dir=/path/to/parent/dir] \
 *     [--description="One line description"] \
 *     [--selector-prefix=myapp] \
 *     [--angular-version=22] \
 *     [--package-manager=npm] \
 *     [--dry-run=true]
 *
 * Requires on PATH: node, npm, git, jq (jq is a runtime dependency of the generated
 * project's hooks, checked here so a broken generated repo isn't produced silently).
 * Requires GITHUB_TOKEN in the environment if --repo is provided.
 */

const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

const REPO_ROOT = path.resolve(__dirname, '..');
const BASE_DIR = path.join(REPO_ROOT, 'base');
const BUNDLES_DIR = path.join(REPO_ROOT, 'bundles');

const AXES = ['auth', 'data-layer', 'state', 'roles', 'deploy-target', 'i18n', 'offline', 'styling', 'e2e'];

// Used only when --angular-version isn't specified (meaning "use whatever `ng new`
// resolves as latest"). This must be kept updated as Angular ships new majors —
// it's used purely for version-constraint validation (minAngularMajor/maxAngularMajor),
// not for anything that affects what actually gets installed.
const ASSUMED_LATEST_ANGULAR_MAJOR = 22;

function resolveAngularMajor(angularVersionArg) {
  if (!angularVersionArg) return ASSUMED_LATEST_ANGULAR_MAJOR;
  const match = String(angularVersionArg).match(/^(\d+)/);
  if (!match) {
    fail(`Could not parse a major version number from --angular-version="${angularVersionArg}".`);
  }
  return parseInt(match[1], 10);
}

// Commands that run for EVERY generated project, regardless of bundle selection —
// company-wide standards, not per-client decisions. Contrast with a bundle's
// `postGenerateCommands`, which only runs when that specific option is selected.
// Added after discovering `ng new` no longer scaffolds ESLint by default (as of the
// Angular CLI version tested against) — CLAUDE.md already instructs the agent to run
// `ng lint`, so without this, every generated project would ship a false promise and a
// non-functional command.
// Added `ng generate environments` after discovering — via a real `ng build` (not just
// `ng lint`/`ng test`) — that `ng new` hasn't scaffolded src/environments/ by default
// since Angular 15. Every data-layer bundle's config file (api.config.ts,
// graphql.config.ts, realtime.config.ts) imports from '../../../environments/environment',
// meaning every project generated by this system before this fix would fail its
// production build. See CONTEXT.md for the full account.
// Pins @angular-eslint/schematics to the SAME major version as the target Angular
// version, rather than leaving it unpinned. Found via research (not assumed): there is
// a documented, filed bug (angular-eslint#2180) where `ng add @angular-eslint/schematics`
// unpinned can fail to resolve the version matching a non-latest target Angular version
// and instead grab the latest regardless — silently installing a mismatched major
// version. @angular-eslint's major version is guaranteed to align 1:1 with Angular's own
// major version (documented, stable policy since Angular v12), so pinning explicitly is
// both safe and necessary for anything other than the true latest.
function getBasePostGenerateCommands(targetAngularMajor) {
  return [
    `ng add @angular-eslint/schematics@${targetAngularMajor} --skip-confirmation`,
    'ng generate environments',
  ];
}

// ---------------------------------------------------------------------------
// Small utilities
// ---------------------------------------------------------------------------

function fail(msg) {
  console.error(`\n❌ ${msg}\n`);
  process.exit(1);
}

function warn(msg) {
  console.warn(`\n⚠️  ${msg}`);
}

function info(msg) {
  console.log(msg);
}

function parseArgs(argv) {
  const args = {};
  for (const raw of argv.slice(2)) {
    const m = raw.match(/^--([^=]+)=([\s\S]*)$/);
    if (m) {
      args[m[1]] = m[2];
    } else if (raw.startsWith('--')) {
      args[raw.slice(2)] = 'true';
    }
  }
  return args;
}

function commandExists(cmd) {
  const result = spawnSync(cmd, ['--version'], { stdio: 'ignore', shell: process.platform === 'win32' });
  return result.status === 0;
}

function run(cmd, args, opts = {}) {
  const result = spawnSync(cmd, args, { stdio: 'inherit', ...opts });
  return result.status === 0;
}

function runCapture(cmd, args, opts = {}) {
  return spawnSync(cmd, args, { stdio: 'pipe', encoding: 'utf8', ...opts });
}

// ---------------------------------------------------------------------------
// Step 1: prerequisites
// ---------------------------------------------------------------------------

function checkPrerequisites() {
  info('🔎 Checking prerequisites...');
  const required = ['node', 'npm', 'git', 'jq'];
  const missing = required.filter((cmd) => !commandExists(cmd));
  if (missing.length) {
    fail(
      `Missing required tool(s) on PATH: ${missing.join(', ')}.\n` +
        `   - jq is required because the generated project's .claude/hooks read\n` +
        `     .claude/settings.json with it at runtime — a generated repo without jq\n` +
        `     available would have silently non-functional guardrail hooks.`
    );
  }
  info('   ✓ node, npm, git, jq all found.');
}

// ---------------------------------------------------------------------------
// Step 2: load + validate the selection against every bundle's manifest
// ---------------------------------------------------------------------------

function loadManifest(axis, option) {
  const manifestPath = path.join(BUNDLES_DIR, axis, option, 'manifest.json');
  if (!fs.existsSync(manifestPath)) {
    fail(`Unknown bundle option "${option}" for axis "${axis}" (no manifest at ${manifestPath}).`);
  }
  return JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
}

function validateSelection(selection, targetAngularMajor) {
  info('\n🔎 Validating bundle selection...');
  const manifests = {};

  for (const axis of AXES) {
    const option = selection[axis];
    if (!option) {
      fail(`Missing --${axis}=<option>. Required axes: ${AXES.join(', ')}.`);
    }
    manifests[axis] = loadManifest(axis, option);
  }

  // Validate every bundle's `requires` field against the full selection.
  // This is a hard requirement per BUNDLE-CONTRACT.md — a mismatch here means an
  // inconsistent repo would otherwise be generated silently.
  let requiresViolation = false;
  for (const axis of AXES) {
    const manifest = manifests[axis];
    if (!manifest.requires) continue;
    for (const [requiredAxis, allowedOptions] of Object.entries(manifest.requires)) {
      const actual = selection[requiredAxis];
      if (!allowedOptions.includes(actual)) {
        console.error(
          `   ✗ ${axis}="${selection[axis]}" requires ${requiredAxis} to be one of ` +
            `[${allowedOptions.join(', ')}], but got "${actual}".`
        );
        requiresViolation = true;
      }
    }
  }
  if (requiresViolation) {
    fail('Invalid bundle combination (see above). Refusing to generate an inconsistent repo.');
  }
  info('   ✓ All cross-bundle "requires" checks passed.');

  // Validate every bundle's minAngularMajor/maxAngularMajor against the resolved
  // target Angular version. Verified, real version floors/ceilings (angular-oauth2-oidc,
  // @ngrx/signals, primeng) — refusing here prevents generating a repo whose
  // dependencies can never actually install.
  let versionViolation = false;
  for (const axis of AXES) {
    const manifest = manifests[axis];
    if (manifest.minAngularMajor && targetAngularMajor < manifest.minAngularMajor) {
      console.error(
        `   ✗ ${axis}="${selection[axis]}" requires Angular >= ${manifest.minAngularMajor}, ` +
          `but target is Angular ${targetAngularMajor}.`
      );
      versionViolation = true;
    }
    if (manifest.maxAngularMajor && targetAngularMajor > manifest.maxAngularMajor) {
      console.error(
        `   ✗ ${axis}="${selection[axis]}" requires Angular <= ${manifest.maxAngularMajor}, ` +
          `but target is Angular ${targetAngularMajor}.`
      );
      versionViolation = true;
    }
  }
  if (versionViolation) {
    fail(
      'Invalid bundle/Angular-version combination (see above). Refusing to generate a repo ' +
        'whose dependencies cannot actually install. Pick a different bundle option or a ' +
        'different --angular-version.'
    );
  }
  info(`   ✓ All bundle/Angular-version (target: ${targetAngularMajor}) checks passed.`);

  // Surface every selected bundle's knownIssues — informational, not blocking.
  // The person running this (developer or the calling skill) must see these; this
  // script does not decide whether to proceed on their behalf.
  for (const axis of AXES) {
    const manifest = manifests[axis];
    if (manifest.knownIssues && manifest.knownIssues.length) {
      warn(`Known issue for ${axis}="${selection[axis]}":`);
      for (const issue of manifest.knownIssues) {
        console.warn(`   ${issue}`);
      }
    }
  }

  return manifests;
}

// ---------------------------------------------------------------------------
// Step 3: scaffold a real Angular CLI workspace
// ---------------------------------------------------------------------------

function scaffoldAngularWorkspace(projectName, outDir, angularVersion) {
  info(`\n📦 Scaffolding a new Angular workspace "${projectName}"...`);
  fs.mkdirSync(outDir, { recursive: true });

  const projectDir = path.join(outDir, projectName);
  if (fs.existsSync(projectDir)) {
    fail(
      `Target directory already exists: ${projectDir}\n` +
        `   Remove it or choose a different --project-name/--out-dir before re-running.`
    );
  }

  const cliSpec = angularVersion ? `@angular/cli@${angularVersion}` : '@angular/cli';
  const args = [
    '-y',
    cliSpec,
    'new',
    projectName,
    '--skip-install',
    '--defaults',
    '--style=scss',
  ];

  const ok = run('npx', args, { cwd: outDir });
  if (!ok) {
    fail(
      "`ng new` failed. See output above. Common causes: (1) Node.js version does not " +
        "meet the installed Angular CLI's minimum requirement — check `npx @angular/cli " +
        'version` output; (2) network access to the npm registry is unavailable.'
    );
  }

  if (!fs.existsSync(path.join(projectDir, 'package.json'))) {
    fail(`Expected a generated project at ${projectDir} but package.json is missing.`);
  }
  info(`   ✓ Workspace created at ${projectDir}`);
  return projectDir;
}

function runBasePostGenerateCommands(projectDir, dryRun, targetAngularMajor) {
  const commands = getBasePostGenerateCommands(targetAngularMajor);
  if (!commands.length) return;

  const cliSpec = `@angular/cli@${targetAngularMajor}`;

  if (dryRun) {
    info('\nℹ️  --dry-run set — skipping base post-generate command(s):');
    for (const cmdString of commands) {
      info(`   (would run) $ ${cmdString}`);
    }
    return;
  }

  info('\n⚙️  Running base post-generate commands (company-wide standards)...');
  for (const cmdString of commands) {
    info(`   $ ${cmdString}`);
    const parts = cmdString.trim().split(/\s+/);
    // Pin every `ng` invocation to the SAME Angular CLI major version this project was
    // scaffolded with — an unpinned `npx @angular/cli` could resolve a different CLI
    // version than what actually built this project, and schematic output can differ
    // across CLI versions.
    const actualCmd = parts[0] === 'ng' ? 'npx' : parts[0];
    const actualArgs = parts[0] === 'ng' ? ['-y', cliSpec, ...parts.slice(1)] : parts.slice(1);
    const ok = run(actualCmd, actualArgs, { cwd: projectDir });
    if (!ok) {
      fail(`Base post-generate command failed: ${cmdString}`);
    }
  }
}

function fixSelectorPrefix(projectDir, selectorPrefix) {
  if (selectorPrefix === 'app') return;

  // 1. The @angular-eslint/schematics generator hardcodes prefix: 'app' (or "app" —
  // found via real testing that the quote style differs by version: v20 emits
  // CommonJS/double-quote style, v21/22 emit ESM/single-quote style) in its lint rules
  // regardless of this project's actual selector prefix. Regex-based, quote-agnostic,
  // rather than a literal string anchor tied to one specific quote style.
  const eslintConfigPath = path.join(projectDir, 'eslint.config.js');
  if (fs.existsSync(eslintConfigPath)) {
    let content = fs.readFileSync(eslintConfigPath, 'utf8');
    content = content.replace(/prefix:\s*(['"])app\1/g, (match, quote) => `prefix: ${quote}${selectorPrefix}${quote}`);
    fs.writeFileSync(eslintConfigPath, content);
  }

  // 2. `ng new` itself always scaffolds the root component with selector 'app-root',
  // regardless of --selector-prefix. Fixing only the lint rule (above) without also
  // fixing the actual root component would make every freshly generated project fail
  // its own lint immediately — found by actually running `ng lint` after combining
  // multiple bundles, not by inspecting the fix in isolation.
  //
  // The root component's FILE NAME itself differs by Angular version — found via real
  // testing: v19 uses the older convention (app.component.ts, class AppComponent),
  // v20+ uses the newer no-suffix convention (app.ts, class App). Check both rather
  // than assuming one.
  for (const candidateName of ['app.ts', 'app.component.ts']) {
    const appTsPath = path.join(projectDir, 'src', 'app', candidateName);
    if (fs.existsSync(appTsPath)) {
      let content = fs.readFileSync(appTsPath, 'utf8');
      content = content.split("selector: 'app-root'").join(`selector: '${selectorPrefix}-root'`);
      fs.writeFileSync(appTsPath, content);
    }
  }

  const indexHtmlPath = path.join(projectDir, 'src', 'index.html');
  if (fs.existsSync(indexHtmlPath)) {
    let content = fs.readFileSync(indexHtmlPath, 'utf8');
    content = content.split('<app-root></app-root>').join(`<${selectorPrefix}-root></${selectorPrefix}-root>`);
    fs.writeFileSync(indexHtmlPath, content);
  }

  info(`   ✓ Fixed selector prefix throughout (lint rule + root component + index.html) to "${selectorPrefix}".`);
}

function tightenEslintRules(projectDir) {
  // @angular-eslint/schematics' default eslint.config.js relies on
  // typescript-eslint's "recommended" preset, which sets no-explicit-any to "warn",
  // not "error" — meaning `any` wouldn't actually fail `ng lint`, contradicting this
  // project's own stated rule ("never use any") and a gap found by cross-checking
  // against an enterprise Angular standards document. This insertion is additive to
  // the existing rules object generated by the schematic, not a wholesale rewrite.
  //
  // NOTE: a `no-console: error` tightening was tried and reverted — it broke on
  // Angular's own default-generated src/main.ts, whose bootstrap error handler is
  // `.catch((err) => console.error(err))`. That's Angular's own idiomatic pattern in
  // every CLI-generated project, not something this system controls — found by
  // actually running the full pipeline end-to-end (git commit failed via the new
  // Husky pre-commit hook), not by reasoning about it in the abstract.
  const eslintConfigPath = path.join(projectDir, 'eslint.config.js');
  if (!fs.existsSync(eslintConfigPath)) return;

  let content = fs.readFileSync(eslintConfigPath, 'utf8');
  // Quote-agnostic: v20's schematic emits double-quoted keys (CommonJS-style output),
  // v21/22 emit single-quoted (ESM-style) — found via real testing, not assumed to be
  // consistent across versions. Match either directly rather than anchoring on one
  // specific quote character.
  const anchorPattern = /rules:\s*\{\s*\n(\s*)(['"])@angular-eslint\/directive-selector\2/;
  const match = content.match(anchorPattern);

  if (match) {
    const [fullMatch, indent, quote] = match;
    const replacement =
      `rules: {\n${indent}${quote}@typescript-eslint/no-explicit-any${quote}: ${quote}error${quote},\n${indent}${quote}@angular-eslint/directive-selector${quote}`;
    content = content.replace(fullMatch, replacement);
    fs.writeFileSync(eslintConfigPath, content);
    info('   ✓ Tightened eslint.config.js: no-explicit-any is now an error, not a warning.');
  } else {
    warn(
      "Could not find the expected anchor in eslint.config.js to tighten no-explicit-any — " +
        'the @angular-eslint/schematics output format may have changed. Skipping this fix-up; flag for review.'
    );
  }
}

// ---------------------------------------------------------------------------
// Step 4: apply base/ (CLAUDE.md + .claude/) with placeholders filled
// ---------------------------------------------------------------------------

function fillPlaceholders(content, values) {
  let out = content;
  for (const [key, value] of Object.entries(values)) {
    out = out.split(`{{${key}}}`).join(value);
  }
  return out;
}

function copyDirRecursive(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirRecursive(s, d);
    } else {
      fs.copyFileSync(s, d);
    }
  }
}

function wireHttpClientAndInterceptors(projectDir, manifests) {
  // CRITICAL FIX, found via a real tester's report (session 24, test-reports/tester-3):
  // provideHttpClient() was NEVER added to app.config.ts by anything in this system —
  // not base, not any bundle's postGenerateCommands. But basic-auth/rest/graphql/saml
  // all generate code (ApiService, AuthService, interceptors) that assumes HttpClient
  // is provided. Every project using one of these would throw a real
  // NullInjectorError the moment it actually ran in a browser — completely invisible
  // to `ng lint`, `ng build`, and unit tests, since tests always supply their own
  // provideHttpClient()/provideHttpClientTesting() in TestBed, masking the real app's
  // brokenness. Only found because a tester manually wired PrimeNG (a *different*,
  // correctly-documented "manual wiring required" bundle) and happened to notice
  // HttpClient was ALSO silently missing while looking closely at app.config.ts.
  //
  // The `needsHttpClient`/`httpInterceptors` manifest fields already existed on
  // several bundles (basic-auth, rest, saml, graphql) before this fix — the data model
  // was already correct, but nothing in generate.js ever actually read it. This
  // function is what was missing, not new bundle-level design.
  const needsHttpClient = AXES.some((axis) => manifests[axis].needsHttpClient);
  if (!needsHttpClient) return;

  const interceptors = [];
  for (const axis of AXES) {
    if (manifests[axis].httpInterceptors) {
      interceptors.push(...manifests[axis].httpInterceptors);
    }
  }

  const appConfigPath = path.join(projectDir, 'src', 'app', 'app.config.ts');
  if (!fs.existsSync(appConfigPath)) {
    warn('app.config.ts not found — skipping HttpClient wiring. Flag for review.');
    return;
  }

  let content = fs.readFileSync(appConfigPath, 'utf8');

  // Idempotency guard — if this has somehow already been wired (shouldn't happen in
  // the normal pipeline, but defensive), don't double-wire it.
  if (content.includes('provideHttpClient')) {
    return;
  }

  const httpClientImport =
    interceptors.length > 0
      ? "import { provideHttpClient, withInterceptors } from '@angular/common/http';\n"
      : "import { provideHttpClient } from '@angular/common/http';\n";
  const interceptorImports = interceptors.map((i) => `import { ${i.importName} } from '${i.importFrom}';\n`).join('');

  // Prepend new imports at the very top — always valid regardless of whatever import
  // structure already exists in the file (single-line, multi-group, etc.).
  content = httpClientImport + interceptorImports + content;

  const providerCall =
    interceptors.length > 0
      ? `provideHttpClient(withInterceptors([${interceptors.map((i) => i.importName).join(', ')}])),`
      : 'provideHttpClient(),';

  const providersMatch = content.match(/providers:\s*\[/);
  if (!providersMatch) {
    warn('Could not find a providers array in app.config.ts — skipping HttpClient wiring. Flag for review.');
    return;
  }
  const insertPos = providersMatch.index + providersMatch[0].length;
  content = content.slice(0, insertPos) + `\n    ${providerCall}` + content.slice(insertPos);

  fs.writeFileSync(appConfigPath, content);
  info(
    `   ✓ Wired provideHttpClient()${
      interceptors.length ? ' with interceptors: ' + interceptors.map((i) => i.importName).join(', ') : ''
    } into app.config.ts (was completely missing before this fix — see CONTEXT.md).`
  );
}

function fixRoleDirectiveSelector(projectDir, selectorPrefix, rolesSelection) {
  // CRITICAL FIX, found via a real tester's report (session 26, test-reports/tester-5):
  // the rbac bundle's has-role.directive.ts ships with selector: '[hasRole]' — no
  // prefix at all. @angular-eslint's directive-selector rule requires every custom
  // directive's selector to start with this project's configured prefix, so this
  // fails `ng lint` on EVERY rbac project out of the box — and since the generator's
  // own initial commit runs `eslint --fix` via the pre-commit hook, this also breaks
  // the generator's own bootstrap commit for every rbac project. Not an artifact of
  // any specific --selector-prefix value either — '[hasRole]' has no prefix even
  // against Angular's own default 'app' prefix.
  //
  // Unlike the root component's selector (a simple string, no corresponding property),
  // this directive uses Angular's structural-directive microsyntax, where
  // `*directiveName="value"` requires an input literally named `directiveName` — so
  // fixing this requires renaming the input property and its internal usage too, not
  // just the selector string.
  if (rolesSelection !== 'rbac') return;

  const directivePath = path.join(projectDir, 'src', 'app', 'core', 'directives', 'has-role.directive.ts');
  if (!fs.existsSync(directivePath)) {
    warn('rbac selected but has-role.directive.ts not found — skipping directive-selector fix. Flag for review.');
    return;
  }

  // Sanitize to a strict camelCase-safe token — selectorPrefix itself is only
  // guaranteed safe for kebab-case component selectors (used as-is elsewhere), not
  // necessarily already lowercase/alphanumeric-only.
  const camelPrefix = selectorPrefix.toLowerCase().replace(/[^a-z0-9]/g, '') || 'app';
  const newName = `${camelPrefix}HasRole`;

  let content = fs.readFileSync(directivePath, 'utf8');
  content = content.split("selector: '[hasRole]'").join(`selector: '[${newName}]'`);
  content = content.split('readonly hasRole = input').join(`readonly ${newName} = input`);
  content = content.split('this.hasRole()').join(`this.${newName}()`);
  content = content.split('*hasRole=').join(`*${newName}=`); // the file's own usage-example comment
  fs.writeFileSync(directivePath, content);

  // roles.md documents the same usage pattern — keep it consistent, not stale.
  const rolesRulePath = path.join(projectDir, '.claude', 'rules', 'roles.md');
  if (fs.existsSync(rolesRulePath)) {
    let rulesContent = fs.readFileSync(rolesRulePath, 'utf8');
    rulesContent = rulesContent.split('*hasRole').join(`*${newName}`);
    fs.writeFileSync(rolesRulePath, rulesContent);
  }

  info(`   ✓ Renamed has-role directive selector to [${newName}] (was unprefixed '[hasRole]', which failed lint on every rbac project).`);
}

function applyBase(projectDir, placeholderValues) {
  info('\n🛡  Applying base .claude guardrail layer...');

  const claudeMdSrc = fs.readFileSync(path.join(BASE_DIR, 'CLAUDE.md'), 'utf8');
  fs.writeFileSync(path.join(projectDir, 'CLAUDE.md'), fillPlaceholders(claudeMdSrc, placeholderValues));

  copyDirRecursive(path.join(BASE_DIR, '.claude'), path.join(projectDir, '.claude'));

  const mcpConfigSrc = path.join(BASE_DIR, '.mcp.json');
  if (fs.existsSync(mcpConfigSrc)) {
    fs.copyFileSync(mcpConfigSrc, path.join(projectDir, '.mcp.json'));
  }

  // Apply placeholder substitution to EVERY file in .claude/rules/, not a hand-picked
  // list. Previously only CLAUDE.md and architecture.md were processed here, which
  // meant a new placeholder added to any other rule file (like {{TEST_RUNNER}} in
  // angular.md) would silently never get filled in. fillPlaceholders() is a no-op for
  // files with no matching tokens, so processing every file is safe.
  const rulesDir = path.join(projectDir, '.claude', 'rules');
  for (const ruleFile of fs.readdirSync(rulesDir)) {
    const ruleFilePath = path.join(rulesDir, ruleFile);
    if (fs.statSync(ruleFilePath).isFile()) {
      fs.writeFileSync(ruleFilePath, fillPlaceholders(fs.readFileSync(ruleFilePath, 'utf8'), placeholderValues));
    }
  }

  // Hooks must be executable — permissions aren't guaranteed to survive a plain copy.
  const hooksDir = path.join(projectDir, '.claude', 'hooks');
  for (const f of fs.readdirSync(hooksDir)) {
    fs.chmodSync(path.join(hooksDir, f), 0o755);
  }

  info('   ✓ CLAUDE.md, .claude/rules/, .claude/settings.json, .claude/hooks/, .mcp.json in place.');
}

// ---------------------------------------------------------------------------
// Step 5: apply each selected bundle
// ---------------------------------------------------------------------------

function mergeUnique(existing, additions) {
  const set = new Set(existing || []);
  for (const item of additions || []) set.add(item);
  return Array.from(set);
}

function copyFilesTreeWithCollisionCheck(filesRoot, currentSrc, destRoot, seenFiles, bundleLabel) {
  for (const entry of fs.readdirSync(currentSrc, { withFileTypes: true })) {
    const s = path.join(currentSrc, entry.name);
    // Always compute the relative path against the ORIGINAL files/ root, not the
    // current recursion level — using currentSrc here would lose one path segment
    // per directory level and silently scatter files at the wrong depth.
    const relFromFilesRoot = path.relative(filesRoot, s);
    const d = path.join(destRoot, relFromFilesRoot);

    if (entry.isDirectory()) {
      fs.mkdirSync(d, { recursive: true });
      copyFilesTreeWithCollisionCheck(filesRoot, s, destRoot, seenFiles, bundleLabel);
    } else {
      if (seenFiles.has(d)) {
        fail(
          `File collision: "${relFromFilesRoot}" was already written by ` +
            `${seenFiles.get(d)}, and ${bundleLabel} tries to write it too. Per ` +
            `BUNDLE-CONTRACT.md this must be resolved at bundle-design time, not silently ` +
            `overwritten here.`
        );
      }
      fs.mkdirSync(path.dirname(d), { recursive: true });
      fs.copyFileSync(s, d);
      seenFiles.set(d, bundleLabel);
    }
  }
}

function applyBundle(projectDir, axis, option, seenFiles) {
  info(`\n📦 Applying bundle: ${axis}/${option}...`);
  const bundleDir = path.join(BUNDLES_DIR, axis, option);
  const bundleLabel = `${axis}/${option}`;

  // deps.fragment.json -> package.json
  const depsFragmentPath = path.join(bundleDir, 'deps.fragment.json');
  if (fs.existsSync(depsFragmentPath)) {
    const fragment = JSON.parse(fs.readFileSync(depsFragmentPath, 'utf8'));
    const pkgPath = path.join(projectDir, 'package.json');
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));

    // A bundle may specify '*' for an @angular/* package to mean "match whatever
    // Angular version this project actually uses" — but npm's '*' means "absolute
    // latest available," not "compatible with what's installed." Found via a real
    // test: '@angular/cdk': '*' resolved to its true latest (22.0.4, requiring
    // @angular/core ^22) against this project's actual installed core (21.2.18),
    // causing a peer-dependency failure npm's own resolver correctly flagged.
    // Fix: resolve '*' for any @angular/* dependency to the exact version already
    // declared for @angular/core in this project, since Angular's own family
    // packages release in lockstep.
    const coreVersion = pkg.dependencies?.['@angular/core'];
    const resolveAngularStar = (deps) => {
      if (!deps) return deps;
      const resolved = { ...deps };
      for (const [name, version] of Object.entries(resolved)) {
        if (version === '*' && name.startsWith('@angular/') && coreVersion) {
          resolved[name] = coreVersion;
        }
      }
      return resolved;
    };

    pkg.dependencies = { ...(pkg.dependencies || {}), ...resolveAngularStar(fragment.dependencies) };
    pkg.devDependencies = { ...(pkg.devDependencies || {}), ...resolveAngularStar(fragment.devDependencies) };
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
  }

  // settings.fragment.json -> .claude/settings.json (merge permission arrays only)
  const settingsFragmentPath = path.join(bundleDir, 'settings.fragment.json');
  if (fs.existsSync(settingsFragmentPath)) {
    const fragment = JSON.parse(fs.readFileSync(settingsFragmentPath, 'utf8'));
    const settingsPath = path.join(projectDir, '.claude', 'settings.json');
    const settings = JSON.parse(fs.readFileSync(settingsPath, 'utf8'));
    for (const key of ['allow', 'ask', 'deny']) {
      if (fragment[key] && fragment[key].length) {
        settings.permissions[key] = mergeUnique(settings.permissions[key], fragment[key]);
      }
    }
    fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + '\n');
  }

  // rules/<axis>.md -> .claude/rules/<axis>.md
  const rulesDir = path.join(bundleDir, 'rules');
  if (fs.existsSync(rulesDir)) {
    for (const f of fs.readdirSync(rulesDir)) {
      fs.copyFileSync(path.join(rulesDir, f), path.join(projectDir, '.claude', 'rules', f));
    }
  }

  // files/ -> project, mirroring paths, with collision detection across bundles
  const filesDir = path.join(bundleDir, 'files');
  if (fs.existsSync(filesDir)) {
    copyFilesTreeWithCollisionCheck(filesDir, filesDir, projectDir, seenFiles, bundleLabel);
  }

  info(`   ✓ ${bundleLabel} applied.`);
}

// ---------------------------------------------------------------------------
// Step 6: postGenerateCommands (e.g. `ng add @angular/ssr`)
// ---------------------------------------------------------------------------

function runPostGenerateCommands(projectDir, manifests, selection, dryRun) {
  for (const axis of AXES) {
    const manifest = manifests[axis];
    if (!manifest.postGenerateCommands || !manifest.postGenerateCommands.length) continue;

    if (dryRun) {
      info(`\nℹ️  --dry-run set — skipping post-generate command(s) for ${axis}/${selection[axis]}:`);
      for (const cmdString of manifest.postGenerateCommands) {
        info(`   (would run) $ ${cmdString}`);
      }
      continue;
    }

    info(`\n⚙️  Running post-generate commands for ${axis}/${selection[axis]}...`);
    for (const cmdString of manifest.postGenerateCommands) {
      info(`   $ ${cmdString}`);
      // Commands are authored as "ng ..." for readability in manifest.json, but `ng`
      // is not guaranteed to be globally installed — run them through the local
      // Angular CLI via npx instead, which the freshly-scaffolded project depends on.
      const parts = cmdString.trim().split(/\s+/);
      const actualCmd = parts[0] === 'ng' ? 'npx' : parts[0];
      const actualArgs = parts[0] === 'ng' ? ['@angular/cli', ...parts.slice(1)] : parts.slice(1);
      const ok = run(actualCmd, actualArgs, { cwd: projectDir });
      if (!ok) {
        fail(`Post-generate command failed: ${cmdString}`);
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Step 7: npm install
// ---------------------------------------------------------------------------

function npmInstall(projectDir) {
  info('\n📥 Running npm install (this may take a while)...');
  const ok = run('npm', ['install'], { cwd: projectDir });
  if (!ok) {
    fail(
      'npm install failed. Common cause: a peer-dependency conflict — check whether the ' +
        'selected `state` bundle (if ngrx-signalstore) has a knownIssues warning above ' +
        'about Angular version compatibility.'
    );
  }
  info('   ✓ Dependencies installed.');
}

function populateEnvironmentFiles(projectDir) {
  // `ng generate environments` creates environment.ts / environment.development.ts
  // containing only `export const environment = {};` — it has no way to know what
  // fields this project's bundles actually need. Populate both with the real fields
  // referenced across the data-layer bundles (apiUrl, graphqlUrl, realtimeUrl) plus
  // `production`. Unused fields for whichever data-layer bundle wasn't selected are
  // harmless placeholders, not a real cost — simpler than conditional logic here.
  const envDir = path.join(projectDir, 'src', 'environments');
  if (!fs.existsSync(envDir)) {
    warn(
      'src/environments/ not found after `ng generate environments` — skipping population. ' +
        'This means any data-layer bundle needing environment.* will fail its production build. Flag for review.'
    );
    return;
  }

  const envFile = (isProd) => `export const environment = {
  production: ${isProd},
  apiUrl: '${isProd ? 'https://api.example.com' : 'http://localhost:3000/api'}',
  graphqlUrl: '${isProd ? 'https://api.example.com/graphql' : 'http://localhost:3000/graphql'}',
  realtimeUrl: '${isProd ? 'wss://api.example.com' : 'ws://localhost:3000'}',
};
`;

  const prodPath = path.join(envDir, 'environment.ts');
  const devPath = path.join(envDir, 'environment.development.ts');
  if (fs.existsSync(prodPath)) fs.writeFileSync(prodPath, envFile(true));
  if (fs.existsSync(devPath)) fs.writeFileSync(devPath, envFile(false));

  info('   ✓ Populated environment.ts/environment.development.ts with placeholder URLs (developer must fill in real values).');
}

function ensurePrettierInstalled(projectDir) {
  // Found via a real Angular 19 test: prettier was never an explicit devDependency
  // anywhere in this system, despite CLAUDE.md claiming "Format: Prettier" as a locked
  // constant and format-and-lint.sh / lint-staged both calling it. It had been silently
  // relying on `npx`'s auto-install-on-demand fallback — which does NOT work inside
  // lint-staged's spawn mechanism (ENOENT, not a slow-but-working auto-install). This is
  // a real, version-independent gap, not specific to v19 — pin it explicitly.
  const pkgPath = path.join(projectDir, 'package.json');
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  pkg.devDependencies = pkg.devDependencies || {};
  if (!pkg.devDependencies.prettier) {
    pkg.devDependencies.prettier = '^3.9.5';
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
    info('   ✓ Added prettier as an explicit devDependency (was previously relying on npx auto-install, which fails inside lint-staged).');
  }
}

function setupHuskyAndLintStaged(projectDir, dryRun) {
  if (dryRun) {
    info('\nℹ️  --dry-run set — skipping Husky/lint-staged setup.');
    return;
  }

  info('\n🪝 Setting up Husky + lint-staged pre-commit hooks...');

  // Add as devDependencies and install — done here (not via a bundle's
  // deps.fragment.json) since this is a Category-A universal standard, not a
  // per-client decision.
  const pkgPath = path.join(projectDir, 'package.json');
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  pkg.devDependencies = pkg.devDependencies || {};
  pkg.devDependencies.husky = pkg.devDependencies.husky || '^9.1.7';
  pkg.devDependencies['lint-staged'] = pkg.devDependencies['lint-staged'] || '^17.0.8';
  pkg.scripts = pkg.scripts || {};
  pkg.scripts.prepare = 'husky';
  // lint-staged config: run on exactly what's staged, not the whole project —
  // fast, and matches what the commit is actually about to introduce.
  pkg['lint-staged'] = {
    '*.ts': ['eslint --fix', 'prettier --write'],
    '*.html': ['prettier --write'],
    '*.scss': ['prettier --write'],
  };
  fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');

  const installOk = run('npm', ['install'], { cwd: projectDir });
  if (!installOk) {
    warn('Failed to install husky/lint-staged — skipping pre-commit hook setup. Not fatal, but flag for review.');
    return;
  }

  // Use the real `husky init` for the tricky part (wiring git's core.hooksPath
  // correctly) rather than hand-constructing .husky/ ourselves — same
  // prefer-the-real-tool principle used for the ssr/i18n/pwa CLI schematics.
  const initOk = run('npx', ['husky', 'init'], { cwd: projectDir });
  if (!initOk) {
    warn('`npx husky init` failed — skipping pre-commit hook customization. Not fatal, but flag for review.');
    return;
  }

  // husky init's default pre-commit just runs `npm test` — replace with
  // lint-staged, which is what this project actually wants to gate commits on.
  const preCommitPath = path.join(projectDir, '.husky', 'pre-commit');
  fs.writeFileSync(preCommitPath, 'npx lint-staged\n');

  info('   ✓ Husky + lint-staged configured: pre-commit runs eslint --fix + prettier on staged files.');
}

function enableZonelessForLegacyVersion(projectDir, targetAngularMajor) {
  // v21+ is zoneless by default already (confirmed via real testing across v19/v20/v21:
  // v21's own `ng new` output has no explicit zoneless provider at all — Angular's
  // default scheduling itself changed at v21, not just the scaffolding). v19/v20 need
  // this done explicitly and correctly, not just "remove zone.js and hope."
  if (targetAngularMajor >= 21) return;

  info(`\n⚡ Angular ${targetAngularMajor} does not default to zoneless — enabling explicitly...`);

  // provideZonelessChangeDetection() was still experimental (different name) at v19,
  // stabilized at v20.2. Verified via angular.dev's own API docs and real package
  // behavior, not assumed.
  const providerName =
    targetAngularMajor === 19 ? 'provideExperimentalZonelessChangeDetection' : 'provideZonelessChangeDetection';

  // 1. Remove zone.js from angular.json polyfills — build AND test targets both have
  // it by default (confirmed via real inspection), and both need it removed.
  const angularJsonPath = path.join(projectDir, 'angular.json');
  const angularJson = JSON.parse(fs.readFileSync(angularJsonPath, 'utf8'));
  const projectKey = Object.keys(angularJson.projects)[0];
  const architect = angularJson.projects[projectKey].architect;
  for (const target of ['build', 'test']) {
    const polyfills = architect?.[target]?.options?.polyfills;
    if (Array.isArray(polyfills)) {
      architect[target].options.polyfills = polyfills.filter((p) => p !== 'zone.js' && p !== 'zone.js/testing');
    }
  }
  fs.writeFileSync(angularJsonPath, JSON.stringify(angularJson, null, 2) + '\n');

  // 2. Remove zone.js from package.json dependencies.
  const pkgPath = path.join(projectDir, 'package.json');
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  if (pkg.dependencies) delete pkg.dependencies['zone.js'];
  fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');

  // 3. Replace the existing provideZoneChangeDetection({ eventCoalescing: true }) call
  // with the correct zoneless provider — both versions scaffold this call by default
  // (confirmed via real generation), and leaving it alongside a zoneless provider would
  // be contradictory. Using literal string replacement, not regex splicing into the
  // providers array — real testing showed v19 formats the array on one line and v20/v21
  // use multi-line, so a format-agnostic approach is safer than assuming line structure.
  const appConfigPath = path.join(projectDir, 'src', 'app', 'app.config.ts');
  if (fs.existsSync(appConfigPath)) {
    let content = fs.readFileSync(appConfigPath, 'utf8');
    const oldCall = 'provideZoneChangeDetection({ eventCoalescing: true })';
    if (content.includes(oldCall)) {
      content = content.split(oldCall).join(`${providerName}()`);
      // The import statement lists the bare identifier separately from the call —
      // replace it too now that the call-site occurrence is already handled above.
      content = content.split('provideZoneChangeDetection').join(providerName);
      fs.writeFileSync(appConfigPath, content);
      info(`   ✓ Replaced provideZoneChangeDetection with ${providerName}() in app.config.ts.`);
    } else {
      warn(
        `Expected to find 'provideZoneChangeDetection({ eventCoalescing: true })' in ` +
          `app.config.ts for Angular ${targetAngularMajor} but didn't — the CLI's scaffolded ` +
          'output may have changed. Zoneless was NOT enabled; flag for review.'
      );
    }
  }

  info(`   ✓ Removed zone.js from angular.json polyfills (build + test) and package.json.`);

  // 4. The CLI-generated root component spec file bootstraps its own TestBed module,
  // separately from app.config.ts — it does NOT inherit the zoneless provider just
  // added there. Left unfixed, `ng test` throws NG0908 ("this configuration requires
  // Zone.js") because the test injector falls back to expecting zone.js, which no
  // longer exists in this project. This was NOT caught by this project's own sandbox
  // testing (no Chrome binary available to actually run Karma) — found via a real
  // `npm test` run on a real machine, during the user's own verification pass. Same
  // dual-candidate-filename handling as the root component fix above (v19:
  // app.component.spec.ts, v20+: app.spec.ts).
  for (const candidateName of ['app.spec.ts', 'app.component.spec.ts']) {
    const specPath = path.join(projectDir, 'src', 'app', candidateName);
    if (!fs.existsSync(specPath)) continue;

    let specContent = fs.readFileSync(specPath, 'utf8');
    const oldModuleConfig = /TestBed\.configureTestingModule\(\{\s*\n(\s*)imports: (\[[^\]]*\]),\s*\n\s*\}\)/;
    const match = specContent.match(oldModuleConfig);

    if (match) {
      const [fullMatch, indent, importsValue] = match;
      const replacement =
        `TestBed.configureTestingModule({\n${indent}imports: ${importsValue},\n${indent}providers: [${providerName}()],\n  })`;
      specContent = specContent.replace(fullMatch, replacement);
      // Add the import — the spec file has no existing @angular/core import to merge
      // into (only '@angular/core/testing' and the component import), so add a new line.
      specContent = `import { ${providerName} } from '@angular/core';\n` + specContent;
      fs.writeFileSync(specPath, specContent);
      info(`   ✓ Added ${providerName}() to ${candidateName}'s TestBed providers (fixes NG0908).`);
    } else {
      warn(
        `Expected to find TestBed.configureTestingModule({ imports: [...] }) in ` +
          `${candidateName} but the pattern didn't match — the CLI's scaffolded spec file ` +
          'may have changed. This project\'s ng test will likely fail with NG0908; flag for review.'
      );
    }
  }
}

// ---------------------------------------------------------------------------
// Step 8: git init, commit, push
// ---------------------------------------------------------------------------

function gitInitCommitPush(projectDir, repoUrl, dryRun) {
  info('\n🔧 Initializing git...');
  run('git', ['init', '-q'], { cwd: projectDir });
  run('git', ['config', 'user.email', 'boilerplate-generator@local'], { cwd: projectDir });
  run('git', ['config', 'user.name', 'Boilerplate Generator'], { cwd: projectDir });
  run('git', ['add', '-A'], { cwd: projectDir });
  // --no-verify: found via a real test report that lint-staged's own transitive
  // dependency (listr2) uses `styleText` from `node:util`, an export only added in
  // Node 20.19 — on older Node this is a hard SyntaxError, not a warning, failing
  // this commit entirely even though every file was already run through
  // format-and-lint during generation itself. The pre-commit hook adds no real value
  // on this specific, generator-authored bootstrap commit (nothing here was written
  // by an AI agent that skipped formatting) — it exists for *future* commits made by
  // a developer/agent working in the generated project, which are unaffected by this
  // flag (it only applies to this one explicit commit call).
  const committed = run(
    'git',
    ['commit', '-q', '--no-verify', '-m', 'chore: initial project generated by boilerplate-generator'],
    { cwd: projectDir }
  );
  if (!committed) {
    fail('git commit failed. See output above.');
  }
  run('git', ['branch', '-M', 'main'], { cwd: projectDir });
  info('   ✓ Committed on branch main.');

  if (!repoUrl) {
    info('\nℹ️  No --repo provided — generated project left local only, not pushed.');
    return;
  }

  if (dryRun) {
    info(`\nℹ️  --dry-run set — skipping push to ${repoUrl}.`);
    return;
  }

  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    fail('GITHUB_TOKEN environment variable is required to push to --repo. Set it and re-run.');
  }

  info(`\n⬆️  Pushing to ${repoUrl}...`);
  const authedUrl = repoUrl.replace(/^https:\/\//, `https://${token}@`);
  run('git', ['remote', 'add', 'origin', authedUrl], { cwd: projectDir });

  const push = runCapture('git', ['push', '-u', 'origin', 'main'], { cwd: projectDir });
  const scrub = (text) => (text ? text.split(token).join('[REDACTED]') : '');
  if (push.stdout) info(scrub(push.stdout));
  if (push.stderr) console.error(scrub(push.stderr));

  // Strip the token back out of the stored remote URL regardless of push outcome.
  run('git', ['remote', 'set-url', 'origin', repoUrl], { cwd: projectDir });

  if (push.status !== 0) {
    fail('git push failed. See output above (token has been redacted).');
  }
  info(`   ✓ Pushed to ${repoUrl}`);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  const args = parseArgs(process.argv);

  if (args.help) {
    console.log(fs.readFileSync(__filename, 'utf8').split('*/')[0].replace('/**', ''));
    process.exit(0);
  }

  checkPrerequisites();

  const selection = {};
  for (const axis of AXES) selection[axis] = args[axis];

  let targetAngularMajor = resolveAngularMajor(args['angular-version']);
  const manifests = validateSelection(selection, targetAngularMajor);

  const projectName = args['project-name'];
  if (!projectName) fail('--project-name=<name> is required.');
  if (!/^[a-z][a-z0-9-]*$/.test(projectName)) {
    fail('--project-name must be lowercase, start with a letter, and contain only letters/numbers/hyphens (Angular CLI naming rule).');
  }

  // Defensive tilde expansion, found via a real user hitting this exact footgun:
  // `--out-dir=~/maxim-final` was passed through LITERALLY (not expanded by their
  // shell) because tilde expansion typically only applies when `~` is the very first
  // character of a whitespace-separated token — inside `--flag=~/path`, the token
  // actually starts with `--out-dir=`, so many shells (confirmed: zsh, in this case)
  // never expand it at all. path.resolve() then treats the literal `~` as just
  // another folder name relative to cwd, silently nesting the output inside the
  // generator repo itself instead of the user's home directory. Handle this
  // ourselves rather than relying on shell behavior that isn't consistent.
  let rawOutDir = args['out-dir'] || process.cwd();
  if (rawOutDir === '~' || rawOutDir.startsWith('~/') || rawOutDir.startsWith('~\\')) {
    rawOutDir = path.join(os.homedir(), rawOutDir.slice(1));
  }
  const outDir = path.resolve(rawOutDir);
  const repoUrl = args.repo || null;
  const dryRun = args['dry-run'] === 'true';
  const selectorPrefix = args['selector-prefix'] || projectName.replace(/-/g, '');

  const bundleSummaryLines = AXES.map((axis) => `- ${manifests[axis].claudeMdSummaryLine}`).join('\n');

  // Vitest only became the default test runner at Angular v21 (verified across
  // sessions 18/21 via real generation) — v19/v20 use Karma. CLAUDE.md/angular.md
  // previously stated "Test runner is Vitest" unconditionally, which was simply false
  // for any legacy-version project. Fixed by making this a real placeholder instead of
  // a hardcoded claim.
  let testRunner = targetAngularMajor >= 21 ? 'Vitest' : 'Karma/Jasmine';

  // Signal Forms (@angular/forms/signals) was introduced experimental at v21 and
  // becomes stable at v22 (verified: angular.dev's own API docs mark schema() as
  // "experimental since v21.0"; multiple v22-era sources confirm stabilization).
  // Angular's own official angular-developer skill states plainly: "Signal Forms are
  // the recommended approach for handling forms in modern Angular applications (v21+)"
  // and "CRITICAL: You MUST use Angular's new Signal Forms API for all form-related
  // functionality" for those versions — this is the official default, not an opt-in
  // exception, which our own guidance previously got backwards. v19/v20 predate Signal
  // Forms entirely (introduced at v21), so Reactive Forms remains correct there.
  //
  // A function, not a pre-built string: the wording embeds the major version number
  // directly, so if the target version gets corrected later (real vs. assumed — see
  // below), re-selecting between two already-built strings would leave stale wording.
  // Recomputing fresh each call avoids that.
  function computeFormsGuidance(major) {
    if (major >= 21) {
      return `- **This project targets Angular ${major >= 22 ? '22 (Signal Forms is stable here)' : "21 (Signal Forms is still marked experimental at this version, but is Angular's own official recommendation for new v21+ projects)"}. Signal Forms (\`@angular/forms/signals\`) is the primary approach for forms in this project — not Reactive Forms.** This is Angular's own stated default for v21+, not an exception to opt into.
- Build the form from a signal model: \`form(mySignal, (path) => { ... schema rules ... })\` returns a \`FieldTree\`. Bind fields in the template with the \`[formField]\` directive (import \`FormField\` from \`@angular/forms/signals\`) — do not manually bind \`value\`/\`(input)\` on a field that has \`[formField]\` applied.
- **Built-in validators** (import from \`@angular/forms/signals\`): \`required\`, \`minLength\`, \`maxLength\`, \`min\`, \`max\`, \`pattern\`, \`email\`. Apply them inside the schema callback against a field's path, not as template attributes.
- Use \`disabled\`, \`hidden\`, \`readonly\` (all schema-level, conditional via a \`when\` callback) for field state — not manual \`[disabled]\` template bindings on a Signal Forms field.
- Use \`submit(formSignal, async (form) => { ... })\` (imported from \`@angular/forms/signals\`) to handle submission — it only invokes the callback when the form is valid, and manages the \`submitting\` state automatically. Don't hand-roll a submit guard checking validity yourself.
- A \`FieldTree\` node (e.g. \`myForm.email\`) is the *structure* — call it as a function (\`myForm.email()\`) to read its *state* signals (\`value\`, \`valid\`, \`touched\`, \`dirty\`, \`errors\`). Don't confuse the two.
- Do not mix imports from \`@angular/forms\` (Reactive/Template-driven) into a Signal Forms component unless deliberately using \`compatForm\` for an incremental migration — Signal Forms is a from-scratch reimplementation, not an extension of Reactive Forms.
- **Custom form controls**: implement Signal Forms' own custom-control pattern (not \`ControlValueAccessor\`, which is the Reactive Forms mechanism) — if unsure of the exact current pattern, use the Angular CLI MCP server's \`search_documentation\` tool rather than guessing, since this is a newer, still-evolving API surface.
- **Submission handler pattern (resolves a real ambiguity found via testing): use an
  explicit \`(submit)\` handler that calls \`event.preventDefault()\` then \`submit(...)\`
  — don't use the \`[formRoot]\` directive together with a separate explicit \`submit()\`
  call** (the interaction between the two is undocumented and risks a double-submit).
  Concrete, verified-working pattern:
  \`\`\`ts
  protected readonly myForm = form(this.draftModel, (path) => {
    required(path.name, { message: 'Name is required' });
  });

  protected onSubmit(event: Event): void {
    event.preventDefault();
    submit(this.myForm, async () => {
      // ... perform the action; return undefined on success, or a server-error
      // object shaped for the form's schema on failure ...
      return undefined;
    });
  }
  \`\`\`
  \`\`\`html
  <form (submit)="onSubmit($event)">
    <input [formField]="myForm.name" />
    @if (myForm.name().touched() && myForm.name().errors().length) {
      <span class="error">{{ myForm.name().errors()[0].message }}</span>
    }
    <button type="submit">Save</button>
  </form>
  \`\`\``;
    }
    return `- Prefer Reactive Forms over Template-driven forms for anything beyond a single trivial input. (Signal Forms doesn't exist yet on Angular ${major} — it was introduced at v21 — so this isn't a choice being made here, just a fact about what's available.)
- **Validators**: prefer Angular's built-in validators (\`Validators.required\`, \`Validators.email\`, \`Validators.pattern\`, etc.) composed via \`Validators.compose()\` over hand-writing regex/logic that duplicates one. Write a custom validator function only for genuinely app-specific rules, and keep it a pure function (input value in, \`ValidationErrors | null\` out) — no side effects, no injected dependencies unless the validator genuinely needs one (in which case use a factory function returning the validator, not a class).
- **Custom form controls** (a component that should work inside a Reactive Form, e.g. a custom date picker): implement \`ControlValueAccessor\` and register it via the \`NG_VALUE_ACCESSOR\` provider token — don't build a component that merely looks like a form control but doesn't integrate with \`formControlName\`/validation/\`disabled\` state.`;
  }

  let formsGuidance = computeFormsGuidance(targetAngularMajor);

  // Zoneless guidance, fixed after a real test report found the previous universal
  // claim was simply wrong for v21+: angular.md asserted every project has an
  // explicit provideZonelessChangeDetection() call in app.config.ts. Verified via a
  // real fresh v21 generation that this is false — v21+ ships zoneless by default
  // (no zone.js polyfill ever added) with NO explicit provider call anywhere. The
  // explicit call only genuinely exists for v19/v20, where enableZonelessForLegacyVersion()
  // adds it ourselves (those versions don't default to zoneless). Rules must describe
  // what's actually in the file, not assume the same shape across every version.
  function computeZonelessGuidance(major) {
    if (major <= 20) {
      return `- This project runs zoneless — **an explicit provider call
  (\`provideZonelessChangeDetection()\` on v20, \`provideExperimentalZonelessChangeDetection()\`
  on v19) is present in \`app.config.ts\`**, added deliberately since Angular ${major}
  doesn't default to zoneless on its own. Do not remove it, and do not add \`zone.js\`
  back to polyfills or \`angular.json\`.
- Because of this, don't rely on implicit change detection from timers/promises the way
  a zone-based app might — a signal update or explicit trigger is what causes re-render.
- **Every \`TestBed.configureTestingModule\` needs the same provider** in its own
  \`providers\` array — skipping this throws \`NG0908: this configuration requires
  Zone.js\`. The generated \`app.component.spec.ts\`/\`app.spec.ts\` already includes it —
  use it as the reference pattern for every new spec file, not just the app-level one.`;
    }
    return `- This project runs zoneless — but on Angular ${major}, **this is the
  default with no explicit provider call at all**. \`app.config.ts\` will NOT contain
  \`provideZonelessChangeDetection()\` or similar, and that's correct, not a bug to fix
  — don't add one "to be safe" or because an example elsewhere shows one (that pattern
  applies to v19/v20 only, where it's genuinely needed). The project is zoneless
  simply because \`zone.js\` was never added to polyfills in the first place — verify
  this directly in \`angular.json\`/\`app.config.ts\` rather than assuming either way.
- Because of this, don't rely on implicit change detection from timers/promises the way
  a zone-based app might — a signal update or explicit trigger is what causes re-render.
- **No \`TestBed.configureTestingModule\` needs a zoneless provider either** — confirmed
  via real testing (19/19 specs passing with zero zoneless provider anywhere) that
  v21+'s default-zoneless behavior needs no explicit opt-in in tests any more than it
  does in \`app.config.ts\`. Don't add \`provideZonelessChangeDetection()\` to a spec
  "just in case" — it isn't needed and isn't what the generated
  \`app.component.spec.ts\`/\`app.spec.ts\` for this version actually does.`;
  }
  let zonelessGuidance = computeZonelessGuidance(targetAngularMajor);

  const placeholderValues = {
    PROJECT_NAME: projectName,
    ONE_LINE_PROJECT_DESCRIPTION: args.description || 'Generated Angular application.',
    ANGULAR_VERSION: args['angular-version'] || 'latest stable',
    TS_VERSION: args['ts-version'] || 'latest',
    PACKAGE_MANAGER: args['package-manager'] || 'npm',
    SELECTOR_PREFIX: selectorPrefix,
    SELECTED_BUNDLES_LIST: bundleSummaryLines,
    TEST_RUNNER: testRunner,
    FORMS_GUIDANCE: formsGuidance,
    ZONELESS_GUIDANCE: zonelessGuidance,
  };

  const projectDir = scaffoldAngularWorkspace(projectName, outDir, args['angular-version']);

  // Re-derive the target version from what `ng new` ACTUALLY scaffolded, not the
  // pre-scaffold guess. Found via a real bug: when --angular-version is omitted,
  // ASSUMED_LATEST_ANGULAR_MAJOR is a constant guess about "current latest," but the
  // real `npx @angular/cli` resolution can differ from that guess (e.g. a local Node
  // version too old for the true latest CLI causes it to silently resolve an older
  // compatible version instead) — this had already been true throughout this project's
  // own testing, but only became a real failure once the ESLint schematic started
  // being pinned to targetAngularMajor explicitly (this session): pinning to a WRONG
  // guessed version broke `ng add`, whereas the previous unpinned call had silently
  // "worked" by accident. Reading the real installed version fixes this for every
  // downstream decision (ESLint pinning, zoneless enablement, Forms guidance, test
  // runner), not just the immediate symptom.
  try {
    const scaffoldedPkg = JSON.parse(fs.readFileSync(path.join(projectDir, 'package.json'), 'utf8'));
    const actualCoreVersion = scaffoldedPkg.dependencies?.['@angular/core'];
    const actualMajorMatch = actualCoreVersion && actualCoreVersion.match(/(\d+)/);
    if (actualMajorMatch) {
      const actualMajor = parseInt(actualMajorMatch[1], 10);
      if (actualMajor !== targetAngularMajor) {
        warn(
          `Requested/assumed Angular ${targetAngularMajor}, but \`ng new\` actually scaffolded ` +
            `Angular ${actualMajor} (@angular/core: ${actualCoreVersion}) — likely a local Node/CLI ` +
            `resolution difference, not a generate.js bug. Using the ACTUAL scaffolded version ` +
            `(${actualMajor}) for every decision from here on (ESLint pinning, zoneless, Forms ` +
            `guidance, test runner), not the original guess.`
        );
        targetAngularMajor = actualMajor;
        testRunner = targetAngularMajor >= 21 ? 'Vitest' : 'Karma/Jasmine';
        formsGuidance = computeFormsGuidance(targetAngularMajor);
        zonelessGuidance = computeZonelessGuidance(targetAngularMajor);
        placeholderValues.TEST_RUNNER = testRunner;
        placeholderValues.FORMS_GUIDANCE = formsGuidance;
        placeholderValues.ZONELESS_GUIDANCE = zonelessGuidance;
      }
    }
  } catch (e) {
    warn(`Could not verify the actually-scaffolded Angular version (${e.message}) — proceeding with the original target.`);
  }

  runBasePostGenerateCommands(projectDir, dryRun, targetAngularMajor);
  if (!dryRun) {
    fixSelectorPrefix(projectDir, selectorPrefix);
    tightenEslintRules(projectDir);
    populateEnvironmentFiles(projectDir);
    enableZonelessForLegacyVersion(projectDir, targetAngularMajor);
    ensurePrettierInstalled(projectDir);
  }

  applyBase(projectDir, placeholderValues);

  const seenFiles = new Map();
  for (const axis of AXES) {
    applyBundle(projectDir, axis, selection[axis], seenFiles);
  }

  if (!dryRun) {
    wireHttpClientAndInterceptors(projectDir, manifests);
    fixRoleDirectiveSelector(projectDir, selectorPrefix, selection.roles);
  }

  runPostGenerateCommands(projectDir, manifests, selection, dryRun);

  if (!dryRun) {
    npmInstall(projectDir);
    setupHuskyAndLintStaged(projectDir, dryRun);
  } else {
    info('\nℹ️  --dry-run set — skipping npm install.');
  }

  gitInitCommitPush(projectDir, repoUrl, dryRun);

  info(`\n✅ Done. Project generated at: ${projectDir}`);
}

main();
