#!/usr/bin/env node
'use strict';

/**
 * generate.js — deterministic assembly of a new Angular project from base/ + bundles/.
 *
 * This script does NOT use AI. Given the same flags, it produces the same output every
 * time. A Claude Code skill is expected to sit in front of this and handle the
 * conversational Q&A, then call this script with plain flags — see CONTEXT.md §2 for
 * why that split exists.
 *
 * Usage:
 *   node generate.js \
 *     --project-name=my-app \
 *     --auth=basic-auth \
 *     --data-layer=rest \
 *     --state=signals-only \
 *     --roles=single-role \
 *     --deploy-target=spa \
 *     --repo=https://github.com/org/my-app.git \
 *     [--out-dir=/path/to/parent/dir] \
 *     [--description="One line description"] \
 *     [--selector-prefix=myapp] \
 *     [--angular-version=22] \
 *     [--package-manager=npm] \
 *     [--dry-run=true]
 *
 * Requires on PATH: node, npm, git, jq (jq is a runtime dependency of the generated
 * project's hooks, checked here so a broken generated repo isn't produced silently).
 * Requires GITHUB_TOKEN in the environment if --repo is provided.
 */

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const REPO_ROOT = path.resolve(__dirname, '..');
const BASE_DIR = path.join(REPO_ROOT, 'base');
const BUNDLES_DIR = path.join(REPO_ROOT, 'bundles');

const AXES = ['auth', 'data-layer', 'state', 'roles', 'deploy-target', 'i18n', 'offline', 'styling'];

// Used only when --angular-version isn't specified (meaning "use whatever `ng new`
// resolves as latest"). This must be kept updated as Angular ships new majors —
// it's used purely for version-constraint validation (minAngularMajor/maxAngularMajor),
// not for anything that affects what actually gets installed.
const ASSUMED_LATEST_ANGULAR_MAJOR = 22;

function resolveAngularMajor(angularVersionArg) {
  if (!angularVersionArg) return ASSUMED_LATEST_ANGULAR_MAJOR;
  const match = String(angularVersionArg).match(/^(\d+)/);
  if (!match) {
    fail(`Could not parse a major version number from --angular-version="${angularVersionArg}".`);
  }
  return parseInt(match[1], 10);
}

// Commands that run for EVERY generated project, regardless of bundle selection —
// company-wide standards, not per-client decisions. Contrast with a bundle's
// `postGenerateCommands`, which only runs when that specific option is selected.
// Added after discovering `ng new` no longer scaffolds ESLint by default (as of the
// Angular CLI version tested against) — CLAUDE.md already instructs the agent to run
// `ng lint`, so without this, every generated project would ship a false promise and a
// non-functional command.
// Added `ng generate environments` after discovering — via a real `ng build` (not just
// `ng lint`/`ng test`) — that `ng new` hasn't scaffolded src/environments/ by default
// since Angular 15. Every data-layer bundle's config file (api.config.ts,
// graphql.config.ts, realtime.config.ts) imports from '../../../environments/environment',
// meaning every project generated by this system before this fix would fail its
// production build. See CONTEXT.md for the full account.
// Pins @angular-eslint/schematics to the SAME major version as the target Angular
// version, rather than leaving it unpinned. Found via research (not assumed): there is
// a documented, filed bug (angular-eslint#2180) where `ng add @angular-eslint/schematics`
// unpinned can fail to resolve the version matching a non-latest target Angular version
// and instead grab the latest regardless — silently installing a mismatched major
// version. @angular-eslint's major version is guaranteed to align 1:1 with Angular's own
// major version (documented, stable policy since Angular v12), so pinning explicitly is
// both safe and necessary for anything other than the true latest.
function getBasePostGenerateCommands(targetAngularMajor) {
  return [
    `ng add @angular-eslint/schematics@${targetAngularMajor} --skip-confirmation`,
    'ng generate environments',
  ];
}

// ---------------------------------------------------------------------------
// Small utilities
// ---------------------------------------------------------------------------

function fail(msg) {
  console.error(`\n❌ ${msg}\n`);
  process.exit(1);
}

function warn(msg) {
  console.warn(`\n⚠️  ${msg}`);
}

function info(msg) {
  console.log(msg);
}

function parseArgs(argv) {
  const args = {};
  for (const raw of argv.slice(2)) {
    const m = raw.match(/^--([^=]+)=([\s\S]*)$/);
    if (m) {
      args[m[1]] = m[2];
    } else if (raw.startsWith('--')) {
      args[raw.slice(2)] = 'true';
    }
  }
  return args;
}

function commandExists(cmd) {
  const result = spawnSync(cmd, ['--version'], { stdio: 'ignore', shell: process.platform === 'win32' });
  return result.status === 0;
}

function run(cmd, args, opts = {}) {
  const result = spawnSync(cmd, args, { stdio: 'inherit', ...opts });
  return result.status === 0;
}

function runCapture(cmd, args, opts = {}) {
  return spawnSync(cmd, args, { stdio: 'pipe', encoding: 'utf8', ...opts });
}

// ---------------------------------------------------------------------------
// Step 1: prerequisites
// ---------------------------------------------------------------------------

function checkPrerequisites() {
  info('🔎 Checking prerequisites...');
  const required = ['node', 'npm', 'git', 'jq'];
  const missing = required.filter((cmd) => !commandExists(cmd));
  if (missing.length) {
    fail(
      `Missing required tool(s) on PATH: ${missing.join(', ')}.\n` +
        `   - jq is required because the generated project's .claude/hooks read\n` +
        `     .claude/settings.json with it at runtime — a generated repo without jq\n` +
        `     available would have silently non-functional guardrail hooks.`
    );
  }
  info('   ✓ node, npm, git, jq all found.');
}

// ---------------------------------------------------------------------------
// Step 2: load + validate the selection against every bundle's manifest
// ---------------------------------------------------------------------------

function loadManifest(axis, option) {
  const manifestPath = path.join(BUNDLES_DIR, axis, option, 'manifest.json');
  if (!fs.existsSync(manifestPath)) {
    fail(`Unknown bundle option "${option}" for axis "${axis}" (no manifest at ${manifestPath}).`);
  }
  return JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
}

function validateSelection(selection, targetAngularMajor) {
  info('\n🔎 Validating bundle selection...');
  const manifests = {};

  for (const axis of AXES) {
    const option = selection[axis];
    if (!option) {
      fail(`Missing --${axis}=<option>. Required axes: ${AXES.join(', ')}.`);
    }
    manifests[axis] = loadManifest(axis, option);
  }

  // Validate every bundle's `requires` field against the full selection.
  // This is a hard requirement per BUNDLE-CONTRACT.md — a mismatch here means an
  // inconsistent repo would otherwise be generated silently.
  let requiresViolation = false;
  for (const axis of AXES) {
    const manifest = manifests[axis];
    if (!manifest.requires) continue;
    for (const [requiredAxis, allowedOptions] of Object.entries(manifest.requires)) {
      const actual = selection[requiredAxis];
      if (!allowedOptions.includes(actual)) {
        console.error(
          `   ✗ ${axis}="${selection[axis]}" requires ${requiredAxis} to be one of ` +
            `[${allowedOptions.join(', ')}], but got "${actual}".`
        );
        requiresViolation = true;
      }
    }
  }
  if (requiresViolation) {
    fail('Invalid bundle combination (see above). Refusing to generate an inconsistent repo.');
  }
  info('   ✓ All cross-bundle "requires" checks passed.');

  // Validate every bundle's minAngularMajor/maxAngularMajor against the resolved
  // target Angular version. Verified, real version floors/ceilings (angular-oauth2-oidc,
  // @ngrx/signals, primeng) — refusing here prevents generating a repo whose
  // dependencies can never actually install.
  let versionViolation = false;
  for (const axis of AXES) {
    const manifest = manifests[axis];
    if (manifest.minAngularMajor && targetAngularMajor < manifest.minAngularMajor) {
      console.error(
        `   ✗ ${axis}="${selection[axis]}" requires Angular >= ${manifest.minAngularMajor}, ` +
          `but target is Angular ${targetAngularMajor}.`
      );
      versionViolation = true;
    }
    if (manifest.maxAngularMajor && targetAngularMajor > manifest.maxAngularMajor) {
      console.error(
        `   ✗ ${axis}="${selection[axis]}" requires Angular <= ${manifest.maxAngularMajor}, ` +
          `but target is Angular ${targetAngularMajor}.`
      );
      versionViolation = true;
    }
  }
  if (versionViolation) {
    fail(
      'Invalid bundle/Angular-version combination (see above). Refusing to generate a repo ' +
        'whose dependencies cannot actually install. Pick a different bundle option or a ' +
        'different --angular-version.'
    );
  }
  info(`   ✓ All bundle/Angular-version (target: ${targetAngularMajor}) checks passed.`);

  // Surface every selected bundle's knownIssues — informational, not blocking.
  // The person running this (developer or the calling skill) must see these; this
  // script does not decide whether to proceed on their behalf.
  for (const axis of AXES) {
    const manifest = manifests[axis];
    if (manifest.knownIssues && manifest.knownIssues.length) {
      warn(`Known issue for ${axis}="${selection[axis]}":`);
      for (const issue of manifest.knownIssues) {
        console.warn(`   ${issue}`);
      }
    }
  }

  return manifests;
}

// ---------------------------------------------------------------------------
// Step 3: scaffold a real Angular CLI workspace
// ---------------------------------------------------------------------------

function scaffoldAngularWorkspace(projectName, outDir, angularVersion) {
  info(`\n📦 Scaffolding a new Angular workspace "${projectName}"...`);
  fs.mkdirSync(outDir, { recursive: true });

  const projectDir = path.join(outDir, projectName);
  if (fs.existsSync(projectDir)) {
    fail(
      `Target directory already exists: ${projectDir}\n` +
        `   Remove it or choose a different --project-name/--out-dir before re-running.`
    );
  }

  const cliSpec = angularVersion ? `@angular/cli@${angularVersion}` : '@angular/cli';
  const args = [
    '-y',
    cliSpec,
    'new',
    projectName,
    '--skip-install',
    '--defaults',
    '--style=scss',
  ];

  const ok = run('npx', args, { cwd: outDir });
  if (!ok) {
    fail(
      "`ng new` failed. See output above. Common causes: (1) Node.js version does not " +
        "meet the installed Angular CLI's minimum requirement — check `npx @angular/cli " +
        'version` output; (2) network access to the npm registry is unavailable.'
    );
  }

  if (!fs.existsSync(path.join(projectDir, 'package.json'))) {
    fail(`Expected a generated project at ${projectDir} but package.json is missing.`);
  }
  info(`   ✓ Workspace created at ${projectDir}`);
  return projectDir;
}

function runBasePostGenerateCommands(projectDir, dryRun, targetAngularMajor) {
  const commands = getBasePostGenerateCommands(targetAngularMajor);
  if (!commands.length) return;

  const cliSpec = `@angular/cli@${targetAngularMajor}`;

  if (dryRun) {
    info('\nℹ️  --dry-run set — skipping base post-generate command(s):');
    for (const cmdString of commands) {
      info(`   (would run) $ ${cmdString}`);
    }
    return;
  }

  info('\n⚙️  Running base post-generate commands (company-wide standards)...');
  for (const cmdString of commands) {
    info(`   $ ${cmdString}`);
    const parts = cmdString.trim().split(/\s+/);
    // Pin every `ng` invocation to the SAME Angular CLI major version this project was
    // scaffolded with — an unpinned `npx @angular/cli` could resolve a different CLI
    // version than what actually built this project, and schematic output can differ
    // across CLI versions.
    const actualCmd = parts[0] === 'ng' ? 'npx' : parts[0];
    const actualArgs = parts[0] === 'ng' ? ['-y', cliSpec, ...parts.slice(1)] : parts.slice(1);
    const ok = run(actualCmd, actualArgs, { cwd: projectDir });
    if (!ok) {
      fail(`Base post-generate command failed: ${cmdString}`);
    }
  }
}

function fixSelectorPrefix(projectDir, selectorPrefix) {
  if (selectorPrefix === 'app') return;

  // 1. The @angular-eslint/schematics generator hardcodes prefix: 'app' (or "app" —
  // found via real testing that the quote style differs by version: v20 emits
  // CommonJS/double-quote style, v21/22 emit ESM/single-quote style) in its lint rules
  // regardless of this project's actual selector prefix. Regex-based, quote-agnostic,
  // rather than a literal string anchor tied to one specific quote style.
  const eslintConfigPath = path.join(projectDir, 'eslint.config.js');
  if (fs.existsSync(eslintConfigPath)) {
    let content = fs.readFileSync(eslintConfigPath, 'utf8');
    content = content.replace(/prefix:\s*(['"])app\1/g, (match, quote) => `prefix: ${quote}${selectorPrefix}${quote}`);
    fs.writeFileSync(eslintConfigPath, content);
  }

  // 2. `ng new` itself always scaffolds the root component with selector 'app-root',
  // regardless of --selector-prefix. Fixing only the lint rule (above) without also
  // fixing the actual root component would make every freshly generated project fail
  // its own lint immediately — found by actually running `ng lint` after combining
  // multiple bundles, not by inspecting the fix in isolation.
  //
  // The root component's FILE NAME itself differs by Angular version — found via real
  // testing: v19 uses the older convention (app.component.ts, class AppComponent),
  // v20+ uses the newer no-suffix convention (app.ts, class App). Check both rather
  // than assuming one.
  for (const candidateName of ['app.ts', 'app.component.ts']) {
    const appTsPath = path.join(projectDir, 'src', 'app', candidateName);
    if (fs.existsSync(appTsPath)) {
      let content = fs.readFileSync(appTsPath, 'utf8');
      content = content.split("selector: 'app-root'").join(`selector: '${selectorPrefix}-root'`);
      fs.writeFileSync(appTsPath, content);
    }
  }

  const indexHtmlPath = path.join(projectDir, 'src', 'index.html');
  if (fs.existsSync(indexHtmlPath)) {
    let content = fs.readFileSync(indexHtmlPath, 'utf8');
    content = content.split('<app-root></app-root>').join(`<${selectorPrefix}-root></${selectorPrefix}-root>`);
    fs.writeFileSync(indexHtmlPath, content);
  }

  info(`   ✓ Fixed selector prefix throughout (lint rule + root component + index.html) to "${selectorPrefix}".`);
}

function tightenEslintRules(projectDir) {
  // @angular-eslint/schematics' default eslint.config.js relies on
  // typescript-eslint's "recommended" preset, which sets no-explicit-any to "warn",
  // not "error" — meaning `any` wouldn't actually fail `ng lint`, contradicting this
  // project's own stated rule ("never use any") and a gap found by cross-checking
  // against an enterprise Angular standards document. This insertion is additive to
  // the existing rules object generated by the schematic, not a wholesale rewrite.
  //
  // NOTE: a `no-console: error` tightening was tried and reverted — it broke on
  // Angular's own default-generated src/main.ts, whose bootstrap error handler is
  // `.catch((err) => console.error(err))`. That's Angular's own idiomatic pattern in
  // every CLI-generated project, not something this system controls — found by
  // actually running the full pipeline end-to-end (git commit failed via the new
  // Husky pre-commit hook), not by reasoning about it in the abstract.
  const eslintConfigPath = path.join(projectDir, 'eslint.config.js');
  if (!fs.existsSync(eslintConfigPath)) return;

  let content = fs.readFileSync(eslintConfigPath, 'utf8');
  // Quote-agnostic: v20's schematic emits double-quoted keys (CommonJS-style output),
  // v21/22 emit single-quoted (ESM-style) — found via real testing, not assumed to be
  // consistent across versions. Match either directly rather than anchoring on one
  // specific quote character.
  const anchorPattern = /rules:\s*\{\s*\n(\s*)(['"])@angular-eslint\/directive-selector\2/;
  const match = content.match(anchorPattern);

  if (match) {
    const [fullMatch, indent, quote] = match;
    const replacement =
      `rules: {\n${indent}${quote}@typescript-eslint/no-explicit-any${quote}: ${quote}error${quote},\n${indent}${quote}@angular-eslint/directive-selector${quote}`;
    content = content.replace(fullMatch, replacement);
    fs.writeFileSync(eslintConfigPath, content);
    info('   ✓ Tightened eslint.config.js: no-explicit-any is now an error, not a warning.');
  } else {
    warn(
      "Could not find the expected anchor in eslint.config.js to tighten no-explicit-any — " +
        'the @angular-eslint/schematics output format may have changed. Skipping this fix-up; flag for review.'
    );
  }
}

// ---------------------------------------------------------------------------
// Step 4: apply base/ (CLAUDE.md + .claude/) with placeholders filled
// ---------------------------------------------------------------------------

function fillPlaceholders(content, values) {
  let out = content;
  for (const [key, value] of Object.entries(values)) {
    out = out.split(`{{${key}}}`).join(value);
  }
  return out;
}

function copyDirRecursive(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirRecursive(s, d);
    } else {
      fs.copyFileSync(s, d);
    }
  }
}

function applyBase(projectDir, placeholderValues) {
  info('\n🛡  Applying base .claude guardrail layer...');

  const claudeMdSrc = fs.readFileSync(path.join(BASE_DIR, 'CLAUDE.md'), 'utf8');
  fs.writeFileSync(path.join(projectDir, 'CLAUDE.md'), fillPlaceholders(claudeMdSrc, placeholderValues));

  copyDirRecursive(path.join(BASE_DIR, '.claude'), path.join(projectDir, '.claude'));

  const mcpConfigSrc = path.join(BASE_DIR, '.mcp.json');
  if (fs.existsSync(mcpConfigSrc)) {
    fs.copyFileSync(mcpConfigSrc, path.join(projectDir, '.mcp.json'));
  }

  // architecture.md is the one other file with a placeholder token ({{SELECTOR_PREFIX}}).
  const archPath = path.join(projectDir, '.claude', 'rules', 'architecture.md');
  fs.writeFileSync(archPath, fillPlaceholders(fs.readFileSync(archPath, 'utf8'), placeholderValues));

  // Hooks must be executable — permissions aren't guaranteed to survive a plain copy.
  const hooksDir = path.join(projectDir, '.claude', 'hooks');
  for (const f of fs.readdirSync(hooksDir)) {
    fs.chmodSync(path.join(hooksDir, f), 0o755);
  }

  info('   ✓ CLAUDE.md, .claude/rules/, .claude/settings.json, .claude/hooks/, .mcp.json in place.');
}

// ---------------------------------------------------------------------------
// Step 5: apply each selected bundle
// ---------------------------------------------------------------------------

function mergeUnique(existing, additions) {
  const set = new Set(existing || []);
  for (const item of additions || []) set.add(item);
  return Array.from(set);
}

function copyFilesTreeWithCollisionCheck(filesRoot, currentSrc, destRoot, seenFiles, bundleLabel) {
  for (const entry of fs.readdirSync(currentSrc, { withFileTypes: true })) {
    const s = path.join(currentSrc, entry.name);
    // Always compute the relative path against the ORIGINAL files/ root, not the
    // current recursion level — using currentSrc here would lose one path segment
    // per directory level and silently scatter files at the wrong depth.
    const relFromFilesRoot = path.relative(filesRoot, s);
    const d = path.join(destRoot, relFromFilesRoot);

    if (entry.isDirectory()) {
      fs.mkdirSync(d, { recursive: true });
      copyFilesTreeWithCollisionCheck(filesRoot, s, destRoot, seenFiles, bundleLabel);
    } else {
      if (seenFiles.has(d)) {
        fail(
          `File collision: "${relFromFilesRoot}" was already written by ` +
            `${seenFiles.get(d)}, and ${bundleLabel} tries to write it too. Per ` +
            `BUNDLE-CONTRACT.md this must be resolved at bundle-design time, not silently ` +
            `overwritten here.`
        );
      }
      fs.mkdirSync(path.dirname(d), { recursive: true });
      fs.copyFileSync(s, d);
      seenFiles.set(d, bundleLabel);
    }
  }
}

function applyBundle(projectDir, axis, option, seenFiles) {
  info(`\n📦 Applying bundle: ${axis}/${option}...`);
  const bundleDir = path.join(BUNDLES_DIR, axis, option);
  const bundleLabel = `${axis}/${option}`;

  // deps.fragment.json -> package.json
  const depsFragmentPath = path.join(bundleDir, 'deps.fragment.json');
  if (fs.existsSync(depsFragmentPath)) {
    const fragment = JSON.parse(fs.readFileSync(depsFragmentPath, 'utf8'));
    const pkgPath = path.join(projectDir, 'package.json');
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));

    // A bundle may specify '*' for an @angular/* package to mean "match whatever
    // Angular version this project actually uses" — but npm's '*' means "absolute
    // latest available," not "compatible with what's installed." Found via a real
    // test: '@angular/cdk': '*' resolved to its true latest (22.0.4, requiring
    // @angular/core ^22) against this project's actual installed core (21.2.18),
    // causing a peer-dependency failure npm's own resolver correctly flagged.
    // Fix: resolve '*' for any @angular/* dependency to the exact version already
    // declared for @angular/core in this project, since Angular's own family
    // packages release in lockstep.
    const coreVersion = pkg.dependencies?.['@angular/core'];
    const resolveAngularStar = (deps) => {
      if (!deps) return deps;
      const resolved = { ...deps };
      for (const [name, version] of Object.entries(resolved)) {
        if (version === '*' && name.startsWith('@angular/') && coreVersion) {
          resolved[name] = coreVersion;
        }
      }
      return resolved;
    };

    pkg.dependencies = { ...(pkg.dependencies || {}), ...resolveAngularStar(fragment.dependencies) };
    pkg.devDependencies = { ...(pkg.devDependencies || {}), ...resolveAngularStar(fragment.devDependencies) };
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
  }

  // settings.fragment.json -> .claude/settings.json (merge permission arrays only)
  const settingsFragmentPath = path.join(bundleDir, 'settings.fragment.json');
  if (fs.existsSync(settingsFragmentPath)) {
    const fragment = JSON.parse(fs.readFileSync(settingsFragmentPath, 'utf8'));
    const settingsPath = path.join(projectDir, '.claude', 'settings.json');
    const settings = JSON.parse(fs.readFileSync(settingsPath, 'utf8'));
    for (const key of ['allow', 'ask', 'deny']) {
      if (fragment[key] && fragment[key].length) {
        settings.permissions[key] = mergeUnique(settings.permissions[key], fragment[key]);
      }
    }
    fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + '\n');
  }

  // rules/<axis>.md -> .claude/rules/<axis>.md
  const rulesDir = path.join(bundleDir, 'rules');
  if (fs.existsSync(rulesDir)) {
    for (const f of fs.readdirSync(rulesDir)) {
      fs.copyFileSync(path.join(rulesDir, f), path.join(projectDir, '.claude', 'rules', f));
    }
  }

  // files/ -> project, mirroring paths, with collision detection across bundles
  const filesDir = path.join(bundleDir, 'files');
  if (fs.existsSync(filesDir)) {
    copyFilesTreeWithCollisionCheck(filesDir, filesDir, projectDir, seenFiles, bundleLabel);
  }

  info(`   ✓ ${bundleLabel} applied.`);
}

// ---------------------------------------------------------------------------
// Step 6: postGenerateCommands (e.g. `ng add @angular/ssr`)
// ---------------------------------------------------------------------------

function runPostGenerateCommands(projectDir, manifests, selection, dryRun) {
  for (const axis of AXES) {
    const manifest = manifests[axis];
    if (!manifest.postGenerateCommands || !manifest.postGenerateCommands.length) continue;

    if (dryRun) {
      info(`\nℹ️  --dry-run set — skipping post-generate command(s) for ${axis}/${selection[axis]}:`);
      for (const cmdString of manifest.postGenerateCommands) {
        info(`   (would run) $ ${cmdString}`);
      }
      continue;
    }

    info(`\n⚙️  Running post-generate commands for ${axis}/${selection[axis]}...`);
    for (const cmdString of manifest.postGenerateCommands) {
      info(`   $ ${cmdString}`);
      // Commands are authored as "ng ..." for readability in manifest.json, but `ng`
      // is not guaranteed to be globally installed — run them through the local
      // Angular CLI via npx instead, which the freshly-scaffolded project depends on.
      const parts = cmdString.trim().split(/\s+/);
      const actualCmd = parts[0] === 'ng' ? 'npx' : parts[0];
      const actualArgs = parts[0] === 'ng' ? ['@angular/cli', ...parts.slice(1)] : parts.slice(1);
      const ok = run(actualCmd, actualArgs, { cwd: projectDir });
      if (!ok) {
        fail(`Post-generate command failed: ${cmdString}`);
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Step 7: npm install
// ---------------------------------------------------------------------------

function npmInstall(projectDir) {
  info('\n📥 Running npm install (this may take a while)...');
  const ok = run('npm', ['install'], { cwd: projectDir });
  if (!ok) {
    fail(
      'npm install failed. Common cause: a peer-dependency conflict — check whether the ' +
        'selected `state` bundle (if ngrx-signalstore) has a knownIssues warning above ' +
        'about Angular version compatibility.'
    );
  }
  info('   ✓ Dependencies installed.');
}

function populateEnvironmentFiles(projectDir) {
  // `ng generate environments` creates environment.ts / environment.development.ts
  // containing only `export const environment = {};` — it has no way to know what
  // fields this project's bundles actually need. Populate both with the real fields
  // referenced across the data-layer bundles (apiUrl, graphqlUrl, realtimeUrl) plus
  // `production`. Unused fields for whichever data-layer bundle wasn't selected are
  // harmless placeholders, not a real cost — simpler than conditional logic here.
  const envDir = path.join(projectDir, 'src', 'environments');
  if (!fs.existsSync(envDir)) {
    warn(
      'src/environments/ not found after `ng generate environments` — skipping population. ' +
        'This means any data-layer bundle needing environment.* will fail its production build. Flag for review.'
    );
    return;
  }

  const envFile = (isProd) => `export const environment = {
  production: ${isProd},
  apiUrl: '${isProd ? 'https://api.example.com' : 'http://localhost:3000/api'}',
  graphqlUrl: '${isProd ? 'https://api.example.com/graphql' : 'http://localhost:3000/graphql'}',
  realtimeUrl: '${isProd ? 'wss://api.example.com' : 'ws://localhost:3000'}',
};
`;

  const prodPath = path.join(envDir, 'environment.ts');
  const devPath = path.join(envDir, 'environment.development.ts');
  if (fs.existsSync(prodPath)) fs.writeFileSync(prodPath, envFile(true));
  if (fs.existsSync(devPath)) fs.writeFileSync(devPath, envFile(false));

  info('   ✓ Populated environment.ts/environment.development.ts with placeholder URLs (developer must fill in real values).');
}

function ensurePrettierInstalled(projectDir) {
  // Found via a real Angular 19 test: prettier was never an explicit devDependency
  // anywhere in this system, despite CLAUDE.md claiming "Format: Prettier" as a locked
  // constant and format-and-lint.sh / lint-staged both calling it. It had been silently
  // relying on `npx`'s auto-install-on-demand fallback — which does NOT work inside
  // lint-staged's spawn mechanism (ENOENT, not a slow-but-working auto-install). This is
  // a real, version-independent gap, not specific to v19 — pin it explicitly.
  const pkgPath = path.join(projectDir, 'package.json');
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  pkg.devDependencies = pkg.devDependencies || {};
  if (!pkg.devDependencies.prettier) {
    pkg.devDependencies.prettier = '^3.9.5';
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
    info('   ✓ Added prettier as an explicit devDependency (was previously relying on npx auto-install, which fails inside lint-staged).');
  }
}

function setupHuskyAndLintStaged(projectDir, dryRun) {
  if (dryRun) {
    info('\nℹ️  --dry-run set — skipping Husky/lint-staged setup.');
    return;
  }

  info('\n🪝 Setting up Husky + lint-staged pre-commit hooks...');

  // Add as devDependencies and install — done here (not via a bundle's
  // deps.fragment.json) since this is a Category-A universal standard, not a
  // per-client decision.
  const pkgPath = path.join(projectDir, 'package.json');
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  pkg.devDependencies = pkg.devDependencies || {};
  pkg.devDependencies.husky = pkg.devDependencies.husky || '^9.1.7';
  pkg.devDependencies['lint-staged'] = pkg.devDependencies['lint-staged'] || '^17.0.8';
  pkg.scripts = pkg.scripts || {};
  pkg.scripts.prepare = 'husky';
  // lint-staged config: run on exactly what's staged, not the whole project —
  // fast, and matches what the commit is actually about to introduce.
  pkg['lint-staged'] = {
    '*.ts': ['eslint --fix', 'prettier --write'],
    '*.html': ['prettier --write'],
    '*.scss': ['prettier --write'],
  };
  fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');

  const installOk = run('npm', ['install'], { cwd: projectDir });
  if (!installOk) {
    warn('Failed to install husky/lint-staged — skipping pre-commit hook setup. Not fatal, but flag for review.');
    return;
  }

  // Use the real `husky init` for the tricky part (wiring git's core.hooksPath
  // correctly) rather than hand-constructing .husky/ ourselves — same
  // prefer-the-real-tool principle used for the ssr/i18n/pwa CLI schematics.
  const initOk = run('npx', ['husky', 'init'], { cwd: projectDir });
  if (!initOk) {
    warn('`npx husky init` failed — skipping pre-commit hook customization. Not fatal, but flag for review.');
    return;
  }

  // husky init's default pre-commit just runs `npm test` — replace with
  // lint-staged, which is what this project actually wants to gate commits on.
  const preCommitPath = path.join(projectDir, '.husky', 'pre-commit');
  fs.writeFileSync(preCommitPath, 'npx lint-staged\n');

  info('   ✓ Husky + lint-staged configured: pre-commit runs eslint --fix + prettier on staged files.');
}

function enableZonelessForLegacyVersion(projectDir, targetAngularMajor) {
  // v21+ is zoneless by default already (confirmed via real testing across v19/v20/v21:
  // v21's own `ng new` output has no explicit zoneless provider at all — Angular's
  // default scheduling itself changed at v21, not just the scaffolding). v19/v20 need
  // this done explicitly and correctly, not just "remove zone.js and hope."
  if (targetAngularMajor >= 21) return;

  info(`\n⚡ Angular ${targetAngularMajor} does not default to zoneless — enabling explicitly...`);

  // provideZonelessChangeDetection() was still experimental (different name) at v19,
  // stabilized at v20.2. Verified via angular.dev's own API docs and real package
  // behavior, not assumed.
  const providerName =
    targetAngularMajor === 19 ? 'provideExperimentalZonelessChangeDetection' : 'provideZonelessChangeDetection';

  // 1. Remove zone.js from angular.json polyfills — build AND test targets both have
  // it by default (confirmed via real inspection), and both need it removed.
  const angularJsonPath = path.join(projectDir, 'angular.json');
  const angularJson = JSON.parse(fs.readFileSync(angularJsonPath, 'utf8'));
  const projectKey = Object.keys(angularJson.projects)[0];
  const architect = angularJson.projects[projectKey].architect;
  for (const target of ['build', 'test']) {
    const polyfills = architect?.[target]?.options?.polyfills;
    if (Array.isArray(polyfills)) {
      architect[target].options.polyfills = polyfills.filter((p) => p !== 'zone.js' && p !== 'zone.js/testing');
    }
  }
  fs.writeFileSync(angularJsonPath, JSON.stringify(angularJson, null, 2) + '\n');

  // 2. Remove zone.js from package.json dependencies.
  const pkgPath = path.join(projectDir, 'package.json');
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  if (pkg.dependencies) delete pkg.dependencies['zone.js'];
  fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');

  // 3. Replace the existing provideZoneChangeDetection({ eventCoalescing: true }) call
  // with the correct zoneless provider — both versions scaffold this call by default
  // (confirmed via real generation), and leaving it alongside a zoneless provider would
  // be contradictory. Using literal string replacement, not regex splicing into the
  // providers array — real testing showed v19 formats the array on one line and v20/v21
  // use multi-line, so a format-agnostic approach is safer than assuming line structure.
  const appConfigPath = path.join(projectDir, 'src', 'app', 'app.config.ts');
  if (fs.existsSync(appConfigPath)) {
    let content = fs.readFileSync(appConfigPath, 'utf8');
    const oldCall = 'provideZoneChangeDetection({ eventCoalescing: true })';
    if (content.includes(oldCall)) {
      content = content.split(oldCall).join(`${providerName}()`);
      // The import statement lists the bare identifier separately from the call —
      // replace it too now that the call-site occurrence is already handled above.
      content = content.split('provideZoneChangeDetection').join(providerName);
      fs.writeFileSync(appConfigPath, content);
      info(`   ✓ Replaced provideZoneChangeDetection with ${providerName}() in app.config.ts.`);
    } else {
      warn(
        `Expected to find 'provideZoneChangeDetection({ eventCoalescing: true })' in ` +
          `app.config.ts for Angular ${targetAngularMajor} but didn't — the CLI's scaffolded ` +
          'output may have changed. Zoneless was NOT enabled; flag for review.'
      );
    }
  }

  info(`   ✓ Removed zone.js from angular.json polyfills (build + test) and package.json.`);
}

// ---------------------------------------------------------------------------
// Step 8: git init, commit, push
// ---------------------------------------------------------------------------

function gitInitCommitPush(projectDir, repoUrl, dryRun) {
  info('\n🔧 Initializing git...');
  run('git', ['init', '-q'], { cwd: projectDir });
  run('git', ['config', 'user.email', 'boilerplate-generator@local'], { cwd: projectDir });
  run('git', ['config', 'user.name', 'Boilerplate Generator'], { cwd: projectDir });
  run('git', ['add', '-A'], { cwd: projectDir });
  const committed = run(
    'git',
    ['commit', '-q', '-m', 'chore: initial project generated by boilerplate-generator'],
    { cwd: projectDir }
  );
  if (!committed) {
    fail('git commit failed. See output above.');
  }
  run('git', ['branch', '-M', 'main'], { cwd: projectDir });
  info('   ✓ Committed on branch main.');

  if (!repoUrl) {
    info('\nℹ️  No --repo provided — generated project left local only, not pushed.');
    return;
  }

  if (dryRun) {
    info(`\nℹ️  --dry-run set — skipping push to ${repoUrl}.`);
    return;
  }

  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    fail('GITHUB_TOKEN environment variable is required to push to --repo. Set it and re-run.');
  }

  info(`\n⬆️  Pushing to ${repoUrl}...`);
  const authedUrl = repoUrl.replace(/^https:\/\//, `https://${token}@`);
  run('git', ['remote', 'add', 'origin', authedUrl], { cwd: projectDir });

  const push = runCapture('git', ['push', '-u', 'origin', 'main'], { cwd: projectDir });
  const scrub = (text) => (text ? text.split(token).join('[REDACTED]') : '');
  if (push.stdout) info(scrub(push.stdout));
  if (push.stderr) console.error(scrub(push.stderr));

  // Strip the token back out of the stored remote URL regardless of push outcome.
  run('git', ['remote', 'set-url', 'origin', repoUrl], { cwd: projectDir });

  if (push.status !== 0) {
    fail('git push failed. See output above (token has been redacted).');
  }
  info(`   ✓ Pushed to ${repoUrl}`);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  const args = parseArgs(process.argv);

  if (args.help) {
    console.log(fs.readFileSync(__filename, 'utf8').split('*/')[0].replace('/**', ''));
    process.exit(0);
  }

  checkPrerequisites();

  const selection = {};
  for (const axis of AXES) selection[axis] = args[axis];

  const targetAngularMajor = resolveAngularMajor(args['angular-version']);
  const manifests = validateSelection(selection, targetAngularMajor);

  const projectName = args['project-name'];
  if (!projectName) fail('--project-name=<name> is required.');
  if (!/^[a-z][a-z0-9-]*$/.test(projectName)) {
    fail('--project-name must be lowercase, start with a letter, and contain only letters/numbers/hyphens (Angular CLI naming rule).');
  }

  const outDir = path.resolve(args['out-dir'] || process.cwd());
  const repoUrl = args.repo || null;
  const dryRun = args['dry-run'] === 'true';
  const selectorPrefix = args['selector-prefix'] || projectName.replace(/-/g, '');

  const bundleSummaryLines = AXES.map((axis) => `- ${manifests[axis].claudeMdSummaryLine}`).join('\n');

  const placeholderValues = {
    PROJECT_NAME: projectName,
    ONE_LINE_PROJECT_DESCRIPTION: args.description || 'Generated Angular application.',
    ANGULAR_VERSION: args['angular-version'] || 'latest stable',
    TS_VERSION: args['ts-version'] || 'latest',
    PACKAGE_MANAGER: args['package-manager'] || 'npm',
    SELECTOR_PREFIX: selectorPrefix,
    SELECTED_BUNDLES_LIST: bundleSummaryLines,
  };

  const projectDir = scaffoldAngularWorkspace(projectName, outDir, args['angular-version']);

  runBasePostGenerateCommands(projectDir, dryRun, targetAngularMajor);
  if (!dryRun) {
    fixSelectorPrefix(projectDir, selectorPrefix);
    tightenEslintRules(projectDir);
    populateEnvironmentFiles(projectDir);
    enableZonelessForLegacyVersion(projectDir, targetAngularMajor);
    ensurePrettierInstalled(projectDir);
  }

  applyBase(projectDir, placeholderValues);

  const seenFiles = new Map();
  for (const axis of AXES) {
    applyBundle(projectDir, axis, selection[axis], seenFiles);
  }

  runPostGenerateCommands(projectDir, manifests, selection, dryRun);

  if (!dryRun) {
    npmInstall(projectDir);
    setupHuskyAndLintStaged(projectDir, dryRun);
  } else {
    info('\nℹ️  --dry-run set — skipping npm install.');
  }

  gitInitCommitPush(projectDir, repoUrl, dryRun);

  info(`\n✅ Done. Project generated at: ${projectDir}`);
}

main();
